version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sld-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: sld_app
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sld-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sld-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://username:password@mongodb:27017/sld_app?authSource=admin
      JWT_SECRET: your-production-jwt-secret-change-this
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - sld-network
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  mongodb_data:

networks:
  sld-network:
    driver: bridge